homepage:
    path: /
    controller: App\Controller\HomeController::indexAction

user_api_get_list:
    path: api/utilisateurs/liste
    controller: App\Controller\ApiController::getAction
    methods: [ GET ]

user_create:
    path: utilisateurs/nouveau
    controller: App\Controller\UserController::newAction
    methods: [ GET, POST ]

user_get_list:
    path: utilisateurs/liste
    controller: App\Controller\UserController::listAction
    methods: [ GET ]